Italian - First Release
counterattackgame/wiki pull request #13
Opened 2021-05-02 20:50 UTC by lorthirk

2021-05-04 20:17 UTC, thomasantonakis requested changes
Return to HomePage needs to be fixed in all pages twice.

2021-05-13 20:15 UTC, lorthirk commented
Everything should be fixed now

2021-05-13 21:35 UTC, counterattackgame reviewed
I think all is good

2021-05-13 21:36 UTC, thomasantonakis approved these changes
Very well.

2021-05-13 21:36 UTC, merged